;BINC v2.3: INFO

info DB 'BINC v2.3 ** BIN to INC Converter ** (c)1995 by ''marikaz''',0Dh,0Ah
DB 'Konwertuje plik do postaci czytelnej dla asemblera. Opis w README.TXT',0Dh,0Ah
DB 0Dh,0Ah
DB 'Skladnia:',0Dh,0Ah
DB 0Dh,0Ah
DB '   BINC.EXE [/N[:][name]] <InFileSpec> [OutFileSpec]',0Dh,0Ah
DB 0Dh,0Ah
DB '/N[:]name    name = nazwa dla wygenerowanej tablicy, max. 15 znakow.',0Dh,0Ah
DB '/N[:]        tablica otrzyma nazwe pliku wejsciowego (bez rozszerzenia).',0Dh,0Ah
DB 'InFileSpec   lokalizacja i/lub nazwa pliku zrodlowego.',0Dh,0Ah
DB 'OutFileSpec  lokalizacja i/lub nazwa pliku docelowego.',0Dh,0Ah
DB 0Dh,0Ah
DB 'W przypadku braku ''OutFileSpec'' zostanie wygenerowany plik z nazwa pliku',0Dh,0Ah
DB 'zrodlowego i rozszerzeniem inc.',0Dh,0Ah
DB 0
